name: application

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branch to deploy'
        required: true

jobs:
  infrastructure:
    name: 'terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: init
        run: |
          cd terraform
          terraform init -backend-config "bucket=${{ secrets.BUCKETS_NAME }}" -backend-config "prefix=${{ secrets.BUCKET_PREFIX }}" -backend-config "credentials=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" -reconfigure

      - name: plan
        id: terraform_plan
        run: |
          cd terraform
          terraform plan -var-file=values.tfvars
          echo ${{ steps.terraform_plan.outputs.stdout }}
          echo ${{ steps.terraform_plan.outputs.stderr }}
          echo ${{ steps.terraform_plan.outputs.exitcode }}

      - name: apply
        id: terraform_apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'main'
        run: |
          terraform apply  -var-file=values.tfvars -auto-approve
          echo ${{ steps.terraform_apply.outputs.stdout }}
          echo ${{ steps.terraform_apply.outputs.stderr }}
          echo ${{ steps.terraform_apply.outputs.exitcode }}

  