name: application

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branch to deploy'
        required: true

jobs:
  infrastructure:
    name: 'terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create credentials file
        run: |
          gcloud iam service-accounts keys create key.json --iam-account=${{ secrets.SA_EMAIL }}

      - name: init
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ secrets.BUCKETS_NAME }}" -backend-config="prefix=${{ secrets.BUCKET_PREFIX}}" -backend-config="credentials=/home/runner/work/devopsprojects/devopsprojects/key.json" -reconfigure

      - name: plan
        id: terraform_plan
        run: |
          cd terraform
          terraform plan -var-file=values.tfvars
          echo ${{ steps.terraform_plan.outputs.stdout }}
          echo ${{ steps.terraform_plan.outputs.stderr }}
          echo ${{ steps.terraform_plan.outputs.exitcode }}

      - name: apply
        id: terraform_apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'main'
        run: |
          terraform apply  -var-file=values.tfvars -auto-approve
          echo ${{ steps.terraform_apply.outputs.stdout }}
          echo ${{ steps.terraform_apply.outputs.stderr }}
          echo ${{ steps.terraform_apply.outputs.exitcode }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: devopsheros137/flight-app:1.0.0
